name: "Bandit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '45 4 * * 5'
   
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      steps:
      - name: Bandit analysis
        uses: jpetrucciani/bandit-check@master
        uses: jpetrucciani/bandit-check@master
        with:
          path: 'backend'
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '-lll -o output.json -f json'
