name: "Bandit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
   
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Bandit Check
        uses: jpetrucciani/bandit-check@1.6.2
        with:
          path: '.'
          #bandit_flags: '-lll -o output.json -f json'
